### ISSUE TITLE
Where to store API keys?

### ISSUE THREAD

**Issue by atenreiro** [valeriouberti/apikey-fastapi#1]
On a production environment, how api keys can be stored? Redis, text file, etc

Thanks

**Comment by valeriouberti** [comment]
In a production environment typically you have your keys in a environment variable. In python you can use dotenv library for retrieve your variables. You can create a settings class like this one:

```import os
from typing import List

from dotenv import load_dotenv
from pydantic_settings import BaseSettings

load_dotenv()

class Settings(BaseSettings):
    API_KEYS: List = os.environ.get("API_KEYS", "changeme").split(",")


settings = Settings()
```

**Comment by atenreiro** [comment]
Hello,

Thanks for the reply. I meant, if I have hundreds of API keys from users, where can they be stored?

**Comment by valeriouberti** [comment]
Ok. In that case you can consider to storing maybe in a secret manager service such as a AWS secret manager or similar.

**Comment by atenreiro** [comment]
Thanks!
